# Generated by Django 5.1.4 on 2024-12-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StadiulComenzii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipStatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenume', models.CharField(max_length=255)),
                ('nume', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('parola', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('tip_statie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipstatie')),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('agent_name', models.CharField(max_length=255)),
                ('code_art', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('final_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dimension', models.CharField(max_length=255, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stadiulcomenzii')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipcomanda')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilizator')),
            ],
        ),
    ]
