# Generated by Django 5.1.4 on 2024-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='department',
            field=models.CharField(choices=[('production', 'Production'), ('sales', 'Sales')], default='production', max_length=50),
        ),
    ]
